import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("plan", models.CharField(default="starter", max_length=32)),
                ("credits", models.PositiveIntegerField(default=20)),
                ("active", models.BooleanField(default=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_organizations", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(choices=[("owner", "Owner"), ("admin", "Admin"), ("member", "Member")], default="member", max_length=16)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="core.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="studio_memberships", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("business_type", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("language", models.CharField(default="de", max_length=10)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("building", "Building"), ("preview", "Preview ready"), ("live", "Live"), ("paused", "Paused"), ("error", "Error")], default="draft", max_length=16)),
                ("app_spec", models.JSONField(blank=True, default=dict)),
                ("repo_url", models.URLField(blank=True)),
                ("repo_name", models.CharField(blank=True, max_length=220)),
                ("desired_domain", models.CharField(blank=True, max_length=255)),
                ("custom_domain", models.CharField(blank=True, max_length=255)),
                ("preview_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("last_build_error", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_studio_projects", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="core.organization")),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("summary", models.TextField(blank=True)),
                ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="conversation", to="core.project")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")], max_length=12)),
                ("content", models.TextField()),
                ("status", models.CharField(choices=[("queued", "Queued"), ("working", "Working"), ("done", "Done"), ("failed", "Failed")], default="done", max_length=12)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="core.conversation")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="FeatureRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField()),
                ("size", models.CharField(choices=[("micro", "Micro"), ("small", "Small"), ("standard", "Standard"), ("advanced", "Advanced"), ("custom", "Custom")], default="small", max_length=16)),
                ("credits", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("proposed", "Proposed"), ("approved", "Approved"), ("building", "Building"), ("done", "Done"), ("rejected", "Rejected"), ("failed", "Failed")], default="proposed", max_length=16)),
                ("before_spec", models.JSONField(blank=True, default=dict)),
                ("after_spec", models.JSONField(blank=True, default=dict)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feature_requests", to="core.project")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("environment", models.CharField(choices=[("preview", "Preview"), ("production", "Production")], max_length=16)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("building", "Building"), ("success", "Success"), ("failed", "Failed"), ("rolled_back", "Rolled back")], default="queued", max_length=16)),
                ("version", models.PositiveIntegerField(default=1)),
                ("url", models.URLField(blank=True)),
                ("log", models.TextField(blank=True)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("feature_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deployments", to="core.featurerequest")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deployments", to="core.project")),
            ],
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("grant", "Grant"), ("purchase", "Purchase"), ("usage", "Usage"), ("refund", "Refund")], max_length=16)),
                ("amount", models.IntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=255)),
                ("external_reference", models.CharField(blank=True, max_length=255)),
                ("feature_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.featurerequest")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_transactions", to="core.organization")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.project")),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="core.organization")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.project")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="StoreSubmission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform", models.CharField(choices=[("android", "Google Play"), ("ios", "Apple App Store"), ("both", "Both stores")], default="both", max_length=16)),
                ("status", models.CharField(choices=[("requested", "Requested"), ("eligibility", "Eligibility review"), ("accounts", "Waiting for developer accounts"), ("preparing", "Preparing package"), ("submitted", "Submitted"), ("review", "In store review"), ("approved", "Approved"), ("rejected", "Rejected")], default="requested", max_length=16)),
                ("notes", models.TextField(blank=True)),
                ("eligibility_report", models.JSONField(blank=True, default=dict)),
                ("quoted_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("external_reference", models.CharField(blank=True, max_length=255)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="store_submissions", to="core.project")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(fields=("organization", "user"), name="unique_org_member"),
        ),
    ]
